Catch Throwable to deal with NoClassDefFoundError (#1863)
Not having certain classes on the classpath results in a
NoClassDefFoundError (that wraps a ClassNotFoundException)
which causes static initialization failure. Protect against
that by catching Throwable instead of Exception.